[pytest]
asyncio_mode = auto
asyncio_default_fixture_loop_scope = session
asyncio_default_test_loop_scope = session
testpaths = tests
markers =
    ui: UI end-to-end tests
    api: API tests
    ui_api: UI + API integration tests (mocked APIs triggered by UI actions)
    smoke: smoke tests
    regression: regression tests
addopts =
    -p no:playwright
    -p no:cacheprovider
    -n auto
    --html=reports/report.html --self-contained-html
    --alluredir=allure_reports/results
    --maxfail=10
    --reruns 1
    --reruns-delay 1
